import { ThemeVariables } from "./theme";

export default function ({}: ThemeVariables) {
  return {
    svg: {
      Notification: require("../theme/assets/svg/Notification.svg"),
      Logo: require("@/src/theme/assets/svg/Logo.svg"),
      First_Line: require("@/src/theme/assets/svg/First_Line.svg"),
      Signin_Text: require("@/src/theme/assets/svg/Signin_Text.svg"),
      Father: require("@/src/theme/assets/svg/Father.svg"),
      Mother: require("@/src/theme/assets/svg/Mother.svg"),
      Children: require("@/src/theme/assets/svg/Childeren.svg"),
      Wife: require("@/src/theme/assets/svg/Wife.svg"),
      Search: require("@/src/theme/assets/svg/Search.svg"),
      Arrow_Left: require("@/src/theme/assets/svg/Arrow_Left.svg"),
      Shopping_Bag: require("@/src/theme/assets/svg/Shopping_Bag.svg"),
      Diamond: require("@/src/theme/assets/svg/Diamond.svg"),
      Watch: require("@/src/theme/assets/svg/Watch.svg"),
      Rolex: require("@/src/theme/assets/svg/Rolex.svg"),
      Omega_Light: require("@/src/theme/assets/svg/Omega_Light.svg"),
      Bling_Banner: require("@/src/theme/assets/svg/Bling_Banner.svg"),
      Home_Tab_Filled: require("@/src/theme/assets/svg/Home_Tab_Filled.svg"),
      Saved_Tab: require("@/src/theme/assets/svg/Saved_Tab.svg"),
      Shop_Tab: require("@/src/theme/assets/svg/Shop_Tab.svg"),
      Account_Tab: require("@/src/theme/assets/svg/Account_Tab.svg"),
      Bling: require("@/src/theme/assets/svg/Bling.svg"),
      Sort: require("@/src/theme/assets/svg/Sort.svg"),
      Grid: require("@/src/theme/assets/svg/Category.svg"),
      Heart: require("@/src/theme/assets/svg/Heart.svg"),
      Eye_Close: require("@/src/theme/assets/svg/Eye_Close.svg"),
      Emoji_Men: require("@/src/theme/assets/svg/Emoji_Men.svg"),
      Emoji_Women: require("@/src/theme/assets/svg/Emoji_Women.svg"),
      Filter: require("@/src/theme/assets/svg/Filter.svg"),
      Arrow_Down: require("@/src/theme/assets/svg/Arrow_Down.svg"),
      Share_Component: require("@/src/theme/assets/svg/Share_Component.svg"),
      Heart_Component: require("@/src/theme/assets/svg/Heart_Component.svg"),
      Heart_Component_Filled: require("@/src/theme/assets/svg/Heart_Component_Filled.svg"),
      List: require("@/src/theme/assets/svg/List.svg"),
      Delivery: require("@/src/theme/assets/svg/Delivery.svg"),
      COD: require("@/src/theme/assets/svg/COD.svg"),
      Return: require("@/src/theme/assets/svg/Return.svg"),
      Location: require("@/src/theme/assets/svg/Location.svg"),
      Buy_Now: require("@/src/theme/assets/svg/Buy_Now.svg"),
      Cross: require("@/src/theme/assets/svg/Cross.svg"),
      DeSelect: require("@/src/theme/assets/svg/DeSelect.svg"),
      Box_Outlined: require("@/src/theme/assets/svg/Box_Outlined.svg"),
      Box_Selected: require("@/src/theme/assets/svg/Box_Selected.svg"),
      Packages: require("@/src/theme/assets/svg/Packages.svg"),
      Eye_Open: require("@/src/theme/assets/svg/Eye_Open.svg"),
      Location_Marker: require("@/src/theme/assets/svg/Location_Marker.svg"),
      Location_Marker_Filled: require("@/src/theme/assets/svg/Location_Marker_Filled.svg"),
      Box: require("@/src/theme/assets/svg/Box.svg"),
      Long_Arrow_Right: require("@/src/theme/assets/svg/Long_Arrow_Right.svg"),
      Logout: require("@/src/theme/assets/svg/Logout.svg"),
      Change_Password: require("@/src/theme/assets/svg/Change_Password.svg"),
      Profile: require("@/src/theme/assets/svg/Profile.svg"),
      Edit: require("@/src/theme/assets/svg/Edit.svg"),
      Complete_Box: require("@/src/theme/assets/svg/Complete_Box.svg"),
      Black_Box: require("@/src/theme/assets/svg/Black_Box.svg"),
      // Delivery screen specific assets
      Message: require("@/src/theme/assets/svg/Message.svg"),
      Phone: require("@/src/theme/assets/svg/Phone.svg"),
      Dots: require("@/src/theme/assets/svg/Dots.svg"),
      Google_Map_Marker: require("@/src/theme/assets/svg/Google_Map_Marker.svg"),
      Map_Box: require("@/src/theme/assets/svg/Map_Box.svg"),
      Slider_Arrows: require("@/src/theme/assets/svg/Slider_Arrows.svg"),
      Progress_Map_Marker: require("@/src/theme/assets/svg/Progress_Map_Marker.svg"),
      Confirm_Order: require("@/src/theme/assets/svg/Confirm_Order.svg"),
      Done_Icon: require("@/src/theme/assets/svg/Done_Icon.svg"),
    },
    png: {
      Logo: require("../theme/assets/images/Logo.png"),
      User: require("../theme/assets/images/User.png"),
      Seller: require("../theme/assets/images/Seller.jpg"),
    },
  };
}
